version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=db_shortlink
      - DB_USERNAME=postgres
      - DB_PASSWORD=Lasmojo123
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped
    networks:
      - shortlink-network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: db_shortlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lasmojo123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
    networks:
      - shortlink-network

networks:
  shortlink-network:
    driver: bridge

volumes:
  pgdata:
